#include <vector>
#include <string>
#include <fstream>
#include <filesystem>
#include "ShaderWriter.h"
#include "Utils.h"

using namespace RB::ShaderCompiler;

static const char* OBJ_FILE_LOCATION = "Shaders.bin";

const char DEFINES_SHADER_START[] = R"(#pragma once
#include <cstdint>
// This file is automatically generated by the shader compiler, do not modify this file in the RabBit project!

namespace RB::ShaderCompiler
{
)";

const char REFLECT_SHADER_START[] = R"(#pragma once
#include <cstdint>
#include "ShaderReflection.h"
// This file is automatically generated by the shader compiler, do not modify this file!

namespace RB::ShaderCompiler
{
	// Relative path from the executable
	static const char* OBJ_FILE_LOCATION = "Shaders.bin";

	static const uint32_t SHADER_ENTRIES = )";

ShaderWriter::ShaderWriter()
{
}

void ShaderWriter::WriteOutShaders(const std::string& defines_folder, const std::string& bin_folder, 
	std::vector<CompiledShader>& shaders, const std::vector<Slang::ComPtr<slang::IBlob>>& blobs)
{
	// Bin file
	{
		std::string bin_filename(bin_folder);
		bin_filename.append("/");
		bin_filename.append(OBJ_FILE_LOCATION);

		std::filesystem::create_directories(bin_folder.c_str());

		std::ofstream bin_file;
		bin_file.open(bin_filename.c_str(), std::fstream::out | std::fstream::trunc | std::fstream::binary);
		EXIT_ON_FAIL(bin_file.is_open(), "Could not open bin directory/file");

		uint64_t offset = 0;
		for (int i = 0; i < shaders.size(); i++)
		{
			CompiledShader& shader = shaders[i];
			Slang::ComPtr<slang::IBlob> blob = blobs[i];

			// Update shader blob info
			shader.shaderBlob.offsetInFile = offset;
			shader.shaderBlob.size = blob->getBufferSize();

			offset += blob->getBufferSize();

			bin_file.write((char*)blob->getBufferPointer(), blob->getBufferSize());
		}

		// Close bin file
		bin_file.close();
	}

	// Start outputting to the defines files
	std::string defines_folder_final = defines_folder;
	defines_folder_final.append("/codeGen");
	std::filesystem::create_directories(defines_folder_final.c_str());

	std::string defines_file_name = defines_folder_final;
	defines_file_name.append("/ShaderDefines.h");

	std::string reflections_file_name = defines_folder_final;
	reflections_file_name.append("/ShaderReflectionDefines.h");

	std::string defines_output;
	defines_output.append(DEFINES_SHADER_START);
	
	std::string reflection_output;
	reflection_output.append(REFLECT_SHADER_START);
	reflection_output.append(std::to_string(shaders.size()));
	reflection_output.append(";\n\t");
	reflection_output.append("static const CompiledShader SHADERS_LOOKUP[] = {");

	for (int shader_idx = 0; shader_idx < shaders.size(); shader_idx++)
	{
		const CompiledShader& shader = shaders[shader_idx];

		defines_output.append("\tstatic const uint32_t ");
		defines_output.append(shader.entryName);
		defines_output.append(" = ");
		defines_output.append(std::to_string(shader_idx));
		defines_output.append(";\n");

		reflection_output.append("{\"");
		reflection_output.append(shader.entryName);
		reflection_output.append("\",(Stage)");
		reflection_output.append(std::to_string((uint32_t)shader.stage));
		reflection_output.append(",{");
		reflection_output.append(std::to_string(shader.shaderBlob.offsetInFile));
		reflection_output.append(",");
		reflection_output.append(std::to_string(shader.shaderBlob.size));
		reflection_output.append("},{");
		for (int i = 0; i < shader.globalParameters.size(); i++)
		{
			const GlobalParameter& par = shader.globalParameters[i];
			reflection_output.append("{\"");
			reflection_output.append(par.name);
			reflection_output.append("\",(ParamType)");
			reflection_output.append(std::to_string((uint32_t)par.type));
			reflection_output.append(",");
			reflection_output.append(std::to_string(par.bindingIndex));
			reflection_output.append(",");
			reflection_output.append(std::to_string(par.size));
			reflection_output.append("},");
		}
		reflection_output.append("},{");
		for (int i = 0; i < shader.entryPointParameters.size(); i++)
		{
			const EntryParameter& par = shader.entryPointParameters[i];
			reflection_output.append("{\"");
			reflection_output.append(par.name);
			reflection_output.append("\",");
			reflection_output.append(std::to_string(par.bindingOffset));
			reflection_output.append(",");
			reflection_output.append(std::to_string(par.size));
			reflection_output.append("},");
		}
		reflection_output.append("},{");
		for (int i = 0; i < shader.vertexParameters.size(); i++)
		{
			const VertexEntryParameter& par = shader.vertexParameters[i];
			reflection_output.append("{\"");
			reflection_output.append(par.name);
			reflection_output.append("\",\"");
			reflection_output.append(par.semantic);
			reflection_output.append("\",");
			reflection_output.append(std::to_string(par.semanticIndex));
			reflection_output.append(",");
			reflection_output.append(std::to_string(par.elements));
			reflection_output.append(",(ScalarType)");
			reflection_output.append(std::to_string((uint32_t)par.scalarType));
			reflection_output.append(",");
			reflection_output.append(std::to_string(par.size));
			reflection_output.append("},");
		}
		reflection_output.append("}},");
	}
	defines_output.append("}");
	reflection_output.append("};\n}");

	// Defines file
	{
		LOG("Defines output location: " << defines_file_name);
		std::ofstream defines_file(defines_file_name, std::ios::out | std::ios::trunc | std::ios::binary);
		defines_file.write(defines_output.c_str(), sizeof(char)* defines_output.length());
		defines_file.close();
	}

	// Reflection file
	{
		LOG("Reflection defines output location: " << reflections_file_name);
		std::ofstream reflect_file(reflections_file_name, std::ios::out | std::ios::trunc | std::ios::binary);
		reflect_file.write(reflection_output.c_str(), sizeof(char) * reflection_output.length());
		reflect_file.close();
	}
}
