#pragma once

namespace RB::Graphics
{
	enum class ResourceState 
	{
		STATE_COMMON								= 0,
		STATE_VERTEX_AND_CONSTANT_BUFFER			= 1,
		STATE_INDEX_BUFFER							= 2,
		STATE_RENDER_TARGET							= 3,
		STATE_UNORDERED_ACCESS						= 4,
		STATE_DEPTH_WRITE							= 5,
		STATE_DEPTH_READ							= 6,
		STATE_NON_PIXEL_SHADER_RESOURCE				= 7,
		STATE_PIXEL_SHADER_RESOURCE					= 8,
		STATE_COPY_DEST								= 9,
		STATE_COPY_SOURCE							= 10,
		STATE_RAYTRACING_ACCELERATION_STRUCTURE		= 11,
		STATE_GENERIC_READ							= 12,
		STATE_ALL_SHADER_RESOURCE					= 13,
		STATE_PRESENT								= 14,
	};
}