#include <atlbase.h>
#include <dxcapi.h>
#include <d3d12shader.h>
#include <vector>
#include <string>
#include <fstream>
#include "ShaderWriter.h"
#include "Utils.h"

struct ShaderLookup
{
	std::wstring	name;
	uint64_t		offsetInFile;
	uint64_t		lengthInFile;
};

const wchar_t SHADER_START[] = LR"(#pragma once
#include <cstdint>
// This file is automatically generated by the shader compiler, do not modify this file yourself!

const char* OBJ_FILE_LOCATION = "Shaders.bin";

struct ShaderLookup
{
	uint64_t offsetInFile;
	uint64_t lengthInFile;
};

)";

ShaderWriter::ShaderWriter()
{
}

void ShaderWriter::WriteOutShaders(const std::wstring& defines_folder, const std::wstring& bin_folder, const std::vector<Shader>& shaders)
{	
	std::wstring bin_filename(bin_folder);
	bin_filename.append(L"/Shaders.bin");

	std::ofstream bin_file;
	bin_file.open(bin_filename.c_str(), std::ios::out | std::ios::trunc | std::ios::binary);
	EXIT_ON_FAIL(bin_file.is_open(), "Could not open bin file");

	std::vector<ShaderLookup> shader_table;
	uint64_t offset = 0;

	for (const Shader& shader : shaders)
	{
		ShaderLookup entry;
		entry.name			= shader.entryName;
		entry.lengthInFile	= shader.shaderBlob->GetBufferSize();
		entry.offsetInFile	= offset;

		shader_table.push_back(entry);
		offset += entry.lengthInFile;

		bin_file.write((char*) shader.shaderBlob->GetBufferPointer(), shader.shaderBlob->GetBufferSize());
	}

	// Close bin file
	bin_file.close();

	// Start outputting to the defines file
	std::wstring defines_file_name = defines_folder;
	defines_file_name.append(L"/ShaderDefines.h");
	std::ofstream defines_file(defines_file_name, std::ios::out | std::ios::trunc | std::ios::binary);

	std::wstring start_output;
	start_output.append(SHADER_START);
	start_output.append(L"const ShaderLookup SHADER_LUT[] = {");

	std::wstring end_output;

	for (int i = 0; i < shader_table.size(); i++)
	{
		const ShaderLookup& entry = shader_table[i];

		start_output.append(L"{");
		start_output.append(std::to_wstring(entry.offsetInFile));
		start_output.append(L",");
		start_output.append(std::to_wstring(entry.lengthInFile));
		start_output.append(L"},");

		end_output.append(L"const uint32_t ");
		end_output.append(entry.name);
		end_output.append(L" = ");
		end_output.append(std::to_wstring(i));
		end_output.append(L";\n");
	}

	start_output.append(L"};\n\n");

	std::wstring final_output;
	final_output.append(start_output);
	final_output.append(end_output);

	char* output = new char[final_output.length() + 1];
	WcharToChar(final_output.c_str(), output);

	defines_file.write(output, sizeof(char) * final_output.length());
	defines_file.close();

	delete[] output;

	/*
		TODO:
		- Add the shader reading logic to the ShaderSystem class
		- Include shader reflection in ShaderLookup to automatically create PSO's
		- Include handling to include other hlsl and .h files

		https://github.com/microsoft/DirectXShaderCompiler/wiki/Using-dxc.exe-and-dxcompiler.dll
	*/
}
