#include <atlbase.h>
#include <dxcapi.h>
#include <d3d12shader.h>
#include <vector>
#include <string>
#include <fstream>
#include "ShaderWriter.h"
#include "Utils.h"

struct ShaderBlobLookup
{
	std::wstring	name;
	uint64_t		offsetInFile;
	uint64_t		shaderBlobLength;
	uint64_t		reflectionBlobLength;
	uint64_t		cbvMask;
	uint64_t		srvMask;
	uint64_t		uavMask;
	uint64_t		samplerMask;
};

const wchar_t SHADER_START[] = LR"(#pragma once
#include <cstdint>
// This file is automatically generated by the shader compiler, do not modify this file yourself!

namespace RB::Graphics
{
)";

const wchar_t D3D_SHADER_START[] = LR"(#pragma once
#include <cstdint>
// This file is automatically generated by the shader compiler, do not modify this file yourself!

namespace RB::Graphics::D3D12
{
	static const char* SHADER_OBJ_FILE_LOCATION = "Shaders.bin";

	struct ShaderBlobLookup
	{
		uint64_t offsetInFile;
		uint64_t shaderBlobLength;
		uint64_t reflectionBlobLength;
		uint64_t cbvMask;
		uint64_t srvMask;
		uint64_t uavMask;
		uint64_t samplerMask;
	};

	static const uint32_t SHADER_ENTRIES = )";

ShaderWriter::ShaderWriter()
{
}

void ShaderWriter::WriteOutShaders(const std::string& defines_folder, const std::string& d3d_defines_folder, const std::string& bin_folder, const std::vector<Shader>& shaders)
{	
	std::string bin_filename(bin_folder);
	bin_filename.append("/Shaders.bin");

	CreateDirectory(bin_folder.c_str(), NULL);

	std::ofstream bin_file;
	bin_file.open(bin_filename.c_str(), std::fstream::out | std::fstream::trunc | std::fstream::binary);
	EXIT_ON_FAIL(bin_file.is_open(), "Could not open bin directory/file");

	std::vector<ShaderBlobLookup> shader_table;
	uint64_t offset = 0;

	for (const Shader& shader : shaders)
	{
		ShaderBlobLookup entry;
		entry.name					= shader.entryName;
		entry.shaderBlobLength		= shader.shaderBlob->GetBufferSize();
		entry.reflectionBlobLength	= shader.reflection->GetBufferSize();
		entry.offsetInFile			= offset;
		entry.cbvMask				= shader.cbvMask;
		entry.srvMask				= shader.srvMask;
		entry.uavMask				= shader.uavMask;
		entry.samplerMask			= shader.samplerMask;

		shader_table.push_back(entry);
		offset += (entry.shaderBlobLength + entry.reflectionBlobLength);

		bin_file.write((char*) shader.shaderBlob->GetBufferPointer(), shader.shaderBlob->GetBufferSize());
		bin_file.write((char*) shader.reflection->GetBufferPointer(), shader.reflection->GetBufferSize());
	}

	// Close bin file
	bin_file.close();


	// Start outputting to the defines files
	std::string d3d_defines_file_name = d3d_defines_folder;
	d3d_defines_file_name.append("/codeGen");
	std::string defines_file_name = defines_folder;
	defines_file_name.append("/codeGen");

	// Create the directory if it does not already exist
	CreateDirectory(d3d_defines_file_name.c_str(), NULL);
	CreateDirectory(defines_file_name.c_str(), NULL);

	d3d_defines_file_name.append("/ShaderDefines.h");
	defines_file_name.append("/ShaderDefines.h");

	std::wstring d3d_output;
	d3d_output.append(D3D_SHADER_START);
	d3d_output.append(std::to_wstring(shaders.size()));
	d3d_output.append(L";\n\tstatic const ShaderBlobLookup SHADER_LUT[] = {");

	std::wstring defines_output;
	defines_output.append(SHADER_START);

	for (int i = 0; i < shader_table.size(); i++)
	{
		const ShaderBlobLookup& entry = shader_table[i];

		d3d_output.append(L"{");
		d3d_output.append(std::to_wstring(entry.offsetInFile));
		d3d_output.append(L",");
		d3d_output.append(std::to_wstring(entry.shaderBlobLength));
		d3d_output.append(L",");
		d3d_output.append(std::to_wstring(entry.reflectionBlobLength));
		d3d_output.append(L",");
		d3d_output.append(std::to_wstring(entry.cbvMask));
		d3d_output.append(L",");
		d3d_output.append(std::to_wstring(entry.srvMask));
		d3d_output.append(L",");
		d3d_output.append(std::to_wstring(entry.uavMask));
		d3d_output.append(L",");
		d3d_output.append(std::to_wstring(entry.samplerMask));
		d3d_output.append(L"},");

		defines_output.append(L"\tstatic const uint32_t ");
		defines_output.append(entry.name);
		defines_output.append(L" = ");
		defines_output.append(std::to_wstring(i));
		defines_output.append(L";\n");
	}

	// D3D file
	{
		d3d_output.append(L"};\n}");

		std::wstring d3d_final_output;
		d3d_final_output.append(d3d_output);

		char* output = new char[d3d_final_output.length() + 1];
		WcharToChar(d3d_final_output.c_str(), output);

		LOG("D3D defines output location: " << d3d_defines_file_name);
		std::ofstream d3d_defines_file(d3d_defines_file_name, std::ios::out | std::ios::trunc | std::ios::binary);
		d3d_defines_file.write(output, sizeof(char) * d3d_final_output.length());
		d3d_defines_file.close();

		delete[] output;
	}

	// Defines file
	{
		defines_output.append(L"}");

		std::wstring final_output;
		final_output.append(defines_output);

		char* output = new char[final_output.length() + 1];
		WcharToChar(final_output.c_str(), output);

		LOG("Defines output location: " << defines_file_name);
		std::ofstream defines_file(defines_file_name, std::ios::out | std::ios::trunc | std::ios::binary);
		defines_file.write(output, sizeof(char) * final_output.length());
		defines_file.close();
		
		delete[] output;
	}

}
