#pragma once
#include <cstdint>
// This file is automatically generated by the shader compiler, do not modify this file yourself!

namespace RB::Graphics::D3D12
{
	static const char* SHADER_OBJ_FILE_LOCATION = "Shaders.bin";

	struct ShaderBlobLookup
	{
		uint64_t offsetInFile;
		uint64_t shaderBlobLength;
		uint64_t reflectionBlobLength;
	};

	static const uint32_t SHADER_ENTRIES = 2;
	static const ShaderBlobLookup SHADER_LUT[] = {{0,1928,1288},{3216,1760,1260},};

	static const uint32_t VS_VertexColor = 0;
	static const uint32_t PS_VertexColor = 1;
}