#pragma once
#include <cstdint>
// This file is automatically generated by the shader compiler, do not modify this file yourself!

const char* OBJ_FILE_LOCATION = "Shaders.bin";

struct ShaderLookup
{
	uint64_t offsetInFile;
	uint64_t lengthInFile;
};

const ShaderLookup SHADER_LUT[] = {{0,1928},{1928,1760},};

const uint32_t VS_VertexColor = 0;
const uint32_t PS_VertexColor = 1;
