name: Build & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIG_DIST:    MinSizeRel
  BUILD_CONFIG_DEBUG:   Debug
  BUILD_CONFIG_RELEASE: Release


jobs:
  BuildAndTest:
    runs-on: windows-latest

    steps:
    # Setup
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out


    # Distribution
    - name: Distribution build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_CONFIG_DIST}}

    - name: Distribution tests
      working-directory: ${{github.workspace}}/out/Core/tests
      run: ctest


    # Release
    - name: Release build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_CONFIG_RELEASE}}

    - name: Release tests
      working-directory: ${{github.workspace}}/out/Core/tests
      run: ctest


    # Debug
    - name: Debug build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_CONFIG_DEBUG}}

    - name: Debug tests
      working-directory: ${{github.workspace}}/out/Core/tests
      run: ctest
