name: Build & Tests

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  BUILD_CONFIG_DIST:    MinSizeRel
  BUILD_CONFIG_DEBUG:   Debug
  BUILD_CONFIG_RELEASE: Release


jobs:
  Distribution:
    runs-on: windows-latest

    steps:
    # Setup
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out

    # Distribution
    - name: Build shader compiler
      run: cmake --build ${{github.workspace}}/out --target ShaderCompilerD3D12 --config ${{env.BUILD_CONFIG_DIST}}

    - name: Run shader compiler
      run: ${{github.workspace}}\out\Core\shaderCompiler\d3d12\Distribution\ShaderCompilerD3D12.exe -shadersBin ${{github.workspace}}\out\Sample\Distribution

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_CONFIG_DIST}}

    - name: Tests
      working-directory: ${{github.workspace}}/out/Core/tests
      run: ctest



  Release:
    runs-on: windows-latest

    steps:
    # Setup
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out

    # Release
    - name: Build shaders
      run: cmake --build ${{github.workspace}}/out --target ShaderCompilerD3D12 --config ${{env.BUILD_CONFIG_RELEASE}}

    - name: Run shader compiler
      run: ${{github.workspace}}\out\Core\shaderCompiler\d3d12\Release\ShaderCompilerD3D12.exe -shadersBin ${{github.workspace}}\out\Sample\Release

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_CONFIG_RELEASE}}

    - name: Tests
      working-directory: ${{github.workspace}}/out/Core/tests
      run: ctest



  Debug:
    runs-on: windows-latest

    steps:
    # Setup
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/out

    # Debug
    - name: Build shaders
      run: cmake --build ${{github.workspace}}/out --target ShaderCompilerD3D12 --config ${{env.BUILD_CONFIG_DEBUG}}
    
    - name: Run shader compiler
      run: ${{github.workspace}}\out\Core\shaderCompiler\d3d12\Debug\ShaderCompilerD3D12.exe -shadersBin ${{github.workspace}}\out\Sample\Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{env.BUILD_CONFIG_DEBUG}}

    - name: Tests
      working-directory: ${{github.workspace}}/out/Core/tests
      run: ctest
